Namespace: api-gateway
etcdDns: etcd-headless.core.svc.cluster.local
tracingEndpoint: collector.linkerd-jaeger:55678
branchNameTag: "main"
dockerArtifactAccount: "poetoec"
# Default DYNAMOS (old):
# branchNameTag: "main"
# dockerArtifactAccount: "dynamos1"

